### PR TITLE
Remove unused import

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Review by datakurre — APPROVED** [review]

**Comment by datakurre** [comment]
Should I move this to collective?

**Comment by gforcada** [comment]
I leave that up to you, I've been trying to understand why the bundles are generated that way, but I'm not getting anywhere so far :sweat:

**Comment by datakurre** [comment]
What do you mean with “that way”?

I mean that just ask :) I may have had that use case...

**Comment by gforcada** [comment]
Let me try :-)

Basically I wanted to be able to either force no split bundles to be created (so if I have 2 entries, that only 2 js/css files get generated) basically so I could start from a point where I know what will be produced, and from there split it again in several smaller bundles lazy loaded.

In a way it already does it, sort of, the commons is almost empty and there are two autogenerated bundles, which I guess, as the name is just a random hash, that are the *vendor* dependencies of each entry point.

Just for readability purposes, would it be possible to get those vendors get a ``entry_point-vendor-hash.js`` naming? :thinking: that would be great, to at least be able to relate the bundles together.

**Pull request merged**
